version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: educational_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5666:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/educational_app
    command: sh -c "sleep 5 && bunx prisma migrate deploy && bun run seed && bun run start"

volumes:
  postgres_data: