version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: educational_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/educational_app
      - JWT_ACCESS_SECRET=your_jwt_access_secret
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret
      - BCRYPT_SALT_ROUNDS=8
      - PORT=${PORT:-3000}
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always

volumes:
  postgres_data: