version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: educational_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgresql://admin:password@postgres:5432/educational_app
      - JWT_ACCESS_SECRET=your_jwt_access_secret
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret
      - BCRYPT_SALT_ROUNDS=8
    depends_on:
      - postgres
    command: sh -c "sleep 5 && bunx prisma migrate deploy && bun run seed"
    restart: always

volumes:
  postgres_data: